services:
    api:
        build: ./
        ports:
            - "80:8080"
    networks:
        - api_network

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: "videos_user"
            POSTGRES_PASSWORD: "videos_password"
            POSTGRES_DB: "videos"
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        networks:
            - api_network

volumes:
  db-data:

networks:
  api_network:
    driver: bridge
